# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.define "raspi_0" do |machine|
    machine.vm.network "private_network", ip: "192.168.56.100"
  end
  config.vm.define "aruba_1" do |machine|
    machine.vm.network "private_network", ip: "192.168.56.101"
  end
  config.vm.define "aruba_2" do |machine|
    machine.vm.network "private_network", ip: "192.168.56.102"
  end
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = "1"
  end
end
