import sys

def main():
    # 引数の受け取り
    # ap = sys.argv[1]
    # association = sys.argv[2]

    cmd = sys.argv[1:]

    if (len(cmd) == 1) and (cmd[0] == "client" or "clients"):
        ret = "\n\nClient List\n-----------\nName  IP Address     MAC Address        OS    ESSID  Access Point  Channel  Type  Role  IPv6 Address               Signal    Speed (mbps)\n----  ----------     -----------        --    -----  ------------  -------  ----  ----  ------------               ------    ------------      \n172.31.99.74   02:fa:2e:52:25:0b  NOFP  dev    AP2           1        GN    dev   fe80::182a:5f6e:15be:7f65  59(good)  65(good)      \n172.31.99.239  f2:6c:7a:17:da:34  NOFP  dev    AP2           52E      a-HE  dev   fe80::1481:800c:c9ab:7d48  58(good)  1200(good)\nNumber of Clients   :2\nInfo timestamp      :455"
        print(ret)
    elif (len(cmd) == 2) and (cmd[0] == "ap") and (cmd[1] == "association"):
        ret = "\n\nThe phy column shows client's operational capabilities for current association\n\nFlags: H: Hotspot(802.11u) client, K: 802.11K client, M: VHT Mu beam formee, R: 802.11R client, W: WMM client, w: 802.11w client, V: 802.11v BSS trans capable, P: Punctured preamble, U: HE UL Mu-mimo, O: OWE client, S: SAE client, E: Enterprise client, m: Agile Multiband client, C: Cellular Data Capable - network available, c: Cellular Data Capable - network unavailable, T: Individual TWT client, t: Broadcast TWT client\n\nPHY Details: HT   : High throughput;      20: 20MHz;  40: 40MHz; t: turbo-rates (256-QAM)\nVHT  : Very High throughput; 80: 80MHz; 160: 160MHz; 80p80: 80MHz + 80MHz\nHE   : High Efficiency;       80: 80MHz; 160: 160MHz; 80p80: 80MHz + 80MHz\n<n>ss: <n> spatial streams\n\nAssociation Table\n-----------------\nName  bssid              mac                auth  assoc  aid  l-int  essid  vlan-id  phy             assoc. time  num assoc  Flags  DataReady       UAC\n----  -----              ---                ----  -----  ---  -----  -----  -------  ---             -----------  ---------  -----  ---------       ---\nAP4   1c:28:af:ac:dd:10  1a:70:0f:be:6e:49  y     y      3    20     dev    3333     a-HT-20sgi-1ss  1h:7m:30s    1          WV     Yes (Implicit)  0.0.0.0\nAP4   1c:28:af:ac:dd:10  8e:0d:5b:e1:04:35  y     y      2    20     dev    3333     a-HE-80-2ss     1h:30m:56s   1          WV     Yes (Implicit)  0.0.0.0\nAP4   1c:28:af:ac:dd:10  f2:6c:7a:17:da:34  y     y      1    20     dev    3333     a-HE-80-2ss     1h:15m:4s    1          WV     Yes (Implicit)  0.0.0.0\nNum Clients:3"
        print(ret)
    # 適当に処理を実装
    # if (ap == "ap") and (association=="association"):
    # print(ret)
    # if (ap == "ap") and (association=="association"):
    #     ret = " show ap association\n\nThe phy column shows client's operational capabilities for current association\n\nFlags: H: Hotspot(802.11u) client, K: 802.11K client, M: VHT Mu beam formee, R: 802.11R client, W: WMM client, w: 802.11w client, V: 802.11v BSS trans capable, P: Punctured preamble, U: HE UL Mu-mimo, O: OWE client, S: SAE client, E: Enterprise client, m: Agile Multiband client, C: Cellular Data Capable - network available, c: Cellular Data Capable - network unavailable, T: Individual TWT client, t: Broadcast TWT client\n\nPHY Details: HT   : High throughput;      20: 20MHz;  40: 40MHz; t: turbo-rates (256-QAM)\nVHT  : Very High throughput; 80: 80MHz; 160: 160MHz; 80p80: 80MHz + 80MHz\nHE   : High Efficiency;       80: 80MHz; 160: 160MHz; 80p80: 80MHz + 80MHz\n<n>ss: <n> spatial streams\n\nAssociation Table\n-----------------\nName  bssid              mac                auth  assoc  aid  l-int  essid  vlan-id  phy             assoc. time  num assoc  Flags  DataReady       UAC\n----  -----              ---                ----  -----  ---  -----  -----  -------  ---             -----------  ---------  -----  ---------       ---\nAP4   1c:28:af:ac:dd:10  1a:70:0f:be:6e:49  y     y      3    20     dev    3333     a-HT-20sgi-1ss  1h:7m:30s    1          WV     Yes (Implicit)  0.0.0.0\nAP4   1c:28:af:ac:dd:10  8e:0d:5b:e1:04:35  y     y      2    20     dev    3333     a-HE-80-2ss     1h:30m:56s   1          WV     Yes (Implicit)  0.0.0.0\nAP4   1c:28:af:ac:dd:10  f2:6c:7a:17:da:34  y     y      1    20     dev    3333     a-HE-80-2ss     1h:15m:4s    1          WV     Yes (Implicit)  0.0.0.0\nNum Clients:3"
    # print(ret)